HDFS support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,6 +33,11 @@ have_openblas=no
 openblas_path=
 openblas_check=include/openblas_config.h
 
+# HDFS library
+have_hdfs=no
+hdfs_path=
+hdfs_check=include/hdfs.h
+
 # Boost library
 boost_path=
 boost_check=include/boost/test/unit_test.hpp
@@ -121,6 +126,7 @@ default_protobuf="protobuf-3.1.0"
 default_libzips="libzip-1.1.2"
 default_swig="swig-3.0.10"
 default_mpi="mpi"
+default_hdfs="hadoop hadoop-2.7.3"
 
 function default_paths ()
 {
@@ -226,6 +232,11 @@ function find_libzip ()
 function find_mpi ()
 {
     find_dir "$default_mpi" "$mpi_check"
+}
+
+function find_hdfs ()
+{
+    find_dir "$default_hdfs" "$hdfs_check"
 }
 
 function is_hardlinked ()
@@ -363,6 +374,7 @@ function show_help ()
     echo "  --with-py35-path[=directory] $(show_default $(find_python 35))"
     echo "  --with-swig[=directory] $(show_default $(find_swig))"
     echo "  --with-mpi[=directory] $(show_default $(find_mpi))"
+    echo "  --with-hdfs[=directory] $(show_default $(find_hdfs))"
 
     echo "Libraries search path:"
     for head in $(default_paths)
@@ -847,6 +859,28 @@ do
                 fi
             fi
             ;;
+        --with-hdfs*)
+            have_hdfs=yes
+            if test x$optarg = x
+            then
+                hdfs_path=$(find_hdfs)
+                if test x$hdfs_path = x
+                then
+                    echo "Cannot find HDFS directory."
+                    echo "Please specify a value for --with-hdfs"
+                    echo "HDFS can be downloaded from http://hadoop.apache.org/"
+                    exit 1
+                fi
+           else
+               if test $(check_dir $optarg $hdfs_check) = yes
+               then
+                   hdfs_path=$optarg
+               else
+                   echo "Invalid HDFS directory $optarg"
+                   exit 1
+               fi
+           fi
+           ;;
         *)
             echo Invalid option $key
             show_help
@@ -1063,6 +1097,20 @@ then
     fi
 fi
 
+if test x$hdfs_path = x
+then
+    hdfs_path=$(find_hdfs)
+    if test x$hdfs_path = x
+    then
+        echo Cannot locate HDFS library. See
+        echo   https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux#hdfs
+        echo for installation instructions.
+        exit 1
+    else
+        echo Found HDFS at $hdfs_path
+    fi
+fi
+
 config=$build_top/Config.make
 echo Generating $config
 echo "#Configuration file for cntk" > $config
@@ -1126,7 +1174,9 @@ fi
 if test x$mpi_path != x; then
     echo MPI_PATH=$mpi_path >> $config
 fi
-
+if test x$hdfs_path != x; then
+    echo HDFS_PATH=$hdfs_path >> $config
+fi
 if test $enable_asgd = yes ; then
     echo CNTK_ENABLE_ASGD=true >> $config
 fi
